version: '3.3'

services:
  postgres-10-alpine:
    image: postgres:10-alpine
    container_name: postgres-10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: turbo_fit_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      DATABASE_URL: postgres://postgres:admin@postgres-10-alpine:5432/turbo_fit_database
    ports:
      - 5432:5432
    networks:
      - app-connect
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: ../api
    command: npm run dev
    ports:
      - 3333:3333
    restart: always
    depends_on:
      - postgres-10-alpine
    volumes:
      - .:/usr/app
    networks:
      - app-connect

networks:
  app-connect:
    driver: bridge
